export default [{
  'name': '美食',
  'href': '#food',
  'img': 'meishi.jpg'
}, {
  'name': '甜品饮品',
  'href': '#food',
  'img': 'tianpin.jpg'
}, {
  'name': '商店超市',
  'href': '#food',
  'img': 'chaoshi.jpg'
}, {
  'name': '预定早餐',
  'href': '#food',
  'img': 'zaocan.jpg'
}, {
  'name': '果蔬生疏',
  'href': '#food',
  'img': 'shuguo.jpg'
}, {
  'name': '新店特惠',
  'href': '#food',
  'img': 'xindian.jpg'
}, {
  'name': '准时达',
  'href': '#food',
  'img': 'zhunshi.jpg'
}, {
  'name': '下午茶',
  'href': '#food',
  'img': 'xiawu.jpg'
}]
